name: KeeTrayTOTP PR Build

on: [pull_request]

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1

    - name: nuget restore
      run: nuget restore KeeTrayTOTP.sln

    - name: MSBuild
      run: msbuild KeeTrayTOTP.sln /m

    - name: Run tests
      # It looks like the dotnet CLI can no longer build net45 projects? see https://github.com/microsoft/msbuild/issues/4704
      run: dotnet test --no-build

    - name: MSBuild (With Plgx)
      run: msbuild KeeTrayTOTP.sln /p:Configuration=ReleasePlgx

    - name: Upload plgx
      uses: actions/upload-artifact@v4
      with:
        name: KeeTrayTOTP.plgx
        path: KeeTrayTOTP\bin\ReleasePlgx\KeeTrayTOTP.plgx

  build-mono:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install xvfb-run
      run: sudo apt -y install xvfb

    - name: MSBuild
      run: msbuild /t:Restore,Build /target:build

    - name: Run tests
      run: xvfb-run dotnet vstest KeeTrayTOTP.Tests/bin/Debug/KeeTrayTOTP.Tests.dll
