name: "KeeTrayTOTP Pre Release"

# Trigger on master, except when commit is tagged
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'
env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1

    - name: nuget restore
      run: nuget restore KeeTrayTOTP.sln

    - name: MSBuild (With Plgx)
      run: msbuild KeeTrayTOTP.sln /p:Configuration=ReleasePlgx

    - name: Upload plgx
      uses: actions/upload-artifact@v1
      with:
        name: KeeTrayTOTP.plgx
        path: KeeTrayTOTP\bin\ReleasePlgx\KeeTrayTOTP.plgx

    - name: Generate hashes
      run: |
        Add-Content hashes.txt "Filename: KeeTrayTOTP.plgx"
        Add-Content hashes.txt "=========================="
        foreach ($algorithm in (Get-Command Get-FileHash).Parameters["Algorithm"].Attributes[1].ValidValues)
        {
            Add-Content hashes.txt "${algorithm}: $((Get-FileHash KeeTrayTOTP\bin\ReleasePlgx\KeeTrayTOTP.plgx -Algorithm $algorithm).Hash)"
        }
      shell: pwsh
        
    - name: Create prerelease
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
           **/KeeTrayTOTP.plgx
           hashes.txt
